### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by Tordx**
this is a revert branch

### CODE REVIEW

**Review by elisewithvsodev — APPROVED** [review]

**Review by elisewithvsodev — APPROVED** [review]
wow fixed deployment haha

**Review by elisewithvsodev — APPROVED** [review]
let him cook na uli

**Review by slyzex — APPROVED** [review]
Goods

**Review by elisewithvsodev — APPROVED** [review]
akin singa walay bug haha

**Pull request merged**
